### ISSUE TITLE
UIColor colorWithPatternImage with increasing offset

### ISSUE THREAD

**Issue by Skornos** [vinicius-a-ro/ios-color-picker#1]
I am asynchronously downloading a list of square images where each of them represents some color or pattern.

Let's say for example this square (even though you'll see only a triangle, the other part is white): 
![igtyt](https://cloud.githubusercontent.com/assets/2428729/6941955/3e9bac7c-d884-11e4-8dc3-af69b694e5a1.png)

New `UIColor` for downloaded image is created with `colorWithPatternImage`

`convertedColor = [UIColor colorWithPatternImage:image];`

The problem is that each subsequent `UIColor` image has an offset from the previous one and only the first few ones fit in the circle.

![wpnea](https://cloud.githubusercontent.com/assets/2428729/6941991/7c62c572-d884-11e4-8da7-d07e5003f1b0.png)

I cannot understand why do they move for a few points for each new color. Do you have and idea where could be a problem?

Thanks.

**Comment by viniciusaro** [comment]
Hi, I just uploaded an updated version of the control supporting an array of images as input so you can set them directly instead of using `colorWithPatternImage`.

You can check an example on the sample code.
Let me know if that solves the issue for you! 

Thanks.

**Comment by Skornos** [comment]
hi,

i am sorry for the late response. I've solved the issue on my own with resizing each image to fit my colorpicker frame. Anyway looking at your solution, is it possible to combine both - UIColor and UIImage?

The problem is that some of the colors I receive from the API are hex colors and some of them are images which represent more complicated patterns.

Thanks for your great work on the library!

Peter.
